Update sync_education.py
Cast entries to pandas series to enable conversion to lists. addresses error `AttributeError: 'DataFrame' object has no attribute 'str'.` when trying to run function utils.convert_to_stringlist(). Functions expects series but other changes were resulting in a dataframe object being passed instead