Issue 159 - syncing script updates (#81)
* Update sync_publications.py

Drop unused columns and ignore errors when dropping columns

* Update sync_datasets.py

Added new columns for CCKP table schema
Added code to drop unused columns
Added logic to parse link and alias for Synapse-related patterns. Script will preferentially copy an existing Synapse link from the link column to the synapseLink column. If an appropriate link doesn't exist, the script will check if alias is a synId. If true, a new Synapse URL will be constructed and listed in synapseLink

* Update sync_tools.py

Updated columns to match UNION table content and CCKP table schema
Added code to drop unused columns
Added logic to parse multiple tool links for Synapse-related patterns. Script will copy any existing Synapse links from the link columns to the synapseLink column. This can generate a list of links, in format [Link](Synapse URL)

* Update sync_education.py

Added columns for CCKP table schema
Added code to remove unused columns
Added logic to parse link and alias for Synapse-related patterns. Script will preferentially check if alias is a synId. If true, a new Synapse URL will be constructed and listed in synapseLink. If the alias is not a synId, the script will check if the Resource Link is a Synapse URL and copy it to the synapseLink column, if true. Resource links will have the format [synId](URL) for alias match and [Link](URL) if a URL match

* Update portal_tables/sync_datasets.py

Co-authored-by: Verena Chung <9377970+vpchung@users.noreply.github.com>

* Update portal_tables/sync_datasets.py

Co-authored-by: Verena Chung <9377970+vpchung@users.noreply.github.com>

* Update portal_tables/sync_datasets.py

Co-authored-by: Verena Chung <9377970+vpchung@users.noreply.github.com>

* Update portal_tables/sync_tools.py

Co-authored-by: Verena Chung <9377970+vpchung@users.noreply.github.com>

* Update sync_datasets.py

rename columns instead of adding and dropping

* Update sync_education.py

rename columns instead of adding and dropping

* Update sync_publications.py

rename columns instead of adding and dropping

* Update sync_tools.py

rename columns instead of adding and dropping

* Update sync_education.py

Condense alias and url extraction

* Update sync_education.py

adjust order to prefer building url from alias and reformat list comprehension for url capture

* Update sync_education.py

Cast entries to pandas series to enable conversion to lists. addresses error `AttributeError: 'DataFrame' object has no attribute 'str'.` when trying to run function utils.convert_to_stringlist(). Functions expects series but other changes were resulting in a dataframe object being passed instead

* Update sync_publications.py

adjust df.rename input

* Update sync_tools.py

adjust df.rename input

---------

Co-authored-by: Verena Chung <9377970+vpchung@users.noreply.github.com>