Squashed commit of the following:
commit a0e98886325b5c1a203467527743b2f8a89bc259
Author: Orion Banks <49208907+Bankso@users.noreply.github.com>
Date:   Wed Mar 5 12:31:40 2025 -0800

    Update sync_tools.py

    adjust df.rename input

commit b5fc6573bdf04ba18c9016c42eb3ac0fb00861b0
Author: Orion Banks <49208907+Bankso@users.noreply.github.com>
Date:   Wed Mar 5 12:30:16 2025 -0800

    Update sync_publications.py

    adjust df.rename input

commit 1ed981ce8e3cdb16716e00663d49bfd23f2d88cf
Author: Orion Banks <49208907+Bankso@users.noreply.github.com>
Date:   Wed Mar 5 12:16:40 2025 -0800

    Update sync_education.py

    Cast entries to pandas series to enable conversion to lists. addresses error `AttributeError: 'DataFrame' object has no attribute 'str'.` when trying to run function utils.convert_to_stringlist(). Functions expects series but other changes were resulting in a dataframe object being passed instead

commit 93304978ca203e87b49b5de85d0225d095a29ad6
Author: Orion Banks <49208907+Bankso@users.noreply.github.com>
Date:   Tue Mar 4 17:51:19 2025 -0800

    Update sync_education.py

    adjust order to prefer building url from alias and reformat list comprehension for url capture

commit 603c63d15cf45fae793e65051b07a8c20b8555e0
Author: Orion Banks <49208907+Bankso@users.noreply.github.com>
Date:   Tue Mar 4 17:42:24 2025 -0800

    Update sync_education.py

    Condense alias and url extraction

commit dcc267c488e47c8aa6109e8a24925c808a325a32
Author: Orion Banks <49208907+Bankso@users.noreply.github.com>
Date:   Tue Mar 4 17:03:27 2025 -0800

    Update sync_tools.py

    rename columns instead of adding and dropping

commit f22ea9ec5fe1b93f9cedfa1a27e54e9b9a2c166d
Author: Orion Banks <49208907+Bankso@users.noreply.github.com>
Date:   Tue Mar 4 17:03:22 2025 -0800

    Update sync_publications.py

    rename columns instead of adding and dropping

commit c4005f4d6908122fab546fe6ca55386d484461b3
Author: Orion Banks <49208907+Bankso@users.noreply.github.com>
Date:   Tue Mar 4 17:03:08 2025 -0800

    Update sync_education.py

    rename columns instead of adding and dropping

commit 5b0a08b8fcb38e1d8c622f0affb34e9712170565
Author: Orion Banks <49208907+Bankso@users.noreply.github.com>
Date:   Tue Mar 4 17:02:49 2025 -0800

    Update sync_datasets.py

    rename columns instead of adding and dropping

commit 7e9218aaecdc1a78dfa1557dea5d775515b8ca50
Author: Orion Banks <49208907+Bankso@users.noreply.github.com>
Date:   Tue Mar 4 16:45:02 2025 -0800

    Update portal_tables/sync_tools.py

    Co-authored-by: Verena Chung <9377970+vpchung@users.noreply.github.com>

commit 6fe64eb44625c8e28c970b140a3c5d9d27a6e7de
Author: Orion Banks <49208907+Bankso@users.noreply.github.com>
Date:   Tue Mar 4 16:44:02 2025 -0800

    Update portal_tables/sync_datasets.py

    Co-authored-by: Verena Chung <9377970+vpchung@users.noreply.github.com>

commit 6c8cb018fad5e31821fa3c1841427df8327ee94f
Author: Orion Banks <49208907+Bankso@users.noreply.github.com>
Date:   Tue Mar 4 16:43:19 2025 -0800

    Update portal_tables/sync_datasets.py

    Co-authored-by: Verena Chung <9377970+vpchung@users.noreply.github.com>

commit 063f338e29dd87fd19ad20d948dcd3d027959f85
Author: Orion Banks <49208907+Bankso@users.noreply.github.com>
Date:   Tue Mar 4 16:42:12 2025 -0800

    Update portal_tables/sync_datasets.py

    Co-authored-by: Verena Chung <9377970+vpchung@users.noreply.github.com>